---
title: Belamonte
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: vwesterberg@hotmail.com
author: Ville Westberberg
description: 'This is the future website of a future awesome Swiss company by a couple
  awesome Finns.

'
baseurl: ''
url: ''
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
pages:
- news
- about
